- name: Reload daemons # noqa: command-instead-of-module no-changed-when
  ansible.builtin.command: systemctl daemon-reload

- name: Restart keepalived-exporter
  ansible.builtin.service:
    name: keepalived-prometheus-exporter.service
    state: restarted
