- name: Install Nginx
  ansible.builtin.apt:
    name: nginx

- name: Place configuration file
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
#    validate: nginx -t -c %s
  notify: Restart nginx

- name: Start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
