- name: Install Nginx
  ansible.builtin.apt:
    name: nginx

- name: Place configuration file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: '0444'
  notify: Restart nginx

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
