- name: Reload systemd
  shell: systemctl daemon-reload

- name: Restart prometheus-influxdb
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
    enabled: true
