- name: Add grafana repository key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install grafana
  ansible.builtin.apt:
    name: grafana

- name: Place grafana.ini file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    mode: "0600"
  no_log: true
  notify: Restart grafana

- name: Create directories for grafana
  ansible.builtin.file:
    path: '{{ item }}'
    recurse: true
    state: directory
    owner: root
    mode: "0755"
  loop:
    - /etc/grafana/provisioning/dashboards
    - /etc/grafana/provisioning/datasources
  notify: Restart grafana

- name: Copy datasources.yaml
  ansible.builtin.template:
    src: datasources.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
    owner: root
    mode: "0755"
  notify: Restart grafana

- name: Copy dashboards.yaml
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
    owner: root
    mode: "0755"
  notify: Restart grafana

- name: Place dashboard definition files
  ansible.builtin.copy:
    src: '{{ item }}.json'
    dest: '/etc/grafana/provisioning/dashboards/{{ item }}.json'
    owner: root
    mode: "0755"
  loop:
    - main
    - mysql
    - syslog
  notify: Restart grafana

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
