- name: Install dependencies
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Place configuration file
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: "0600"
  no_log: true
  notify: Restart uwsgi

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
