- name: Install dependencies
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Place configuration file
  ansible.builtin.copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uwsgi
    
- name: Start service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
