---
  - name: Initial setup
    hosts: all
    roles:
      - init

- name: Setup DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Setup DNS resolution
  hosts: all
  roles:
    - dns_resolve

- name: Setup database servers
  hosts: db_servers
  roles:
    - mysql

- name: Setup web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
  tags: nginx
