- name: Initial setup
  hosts: all
  become: true
  roles:
    - init
  tags: init

- name: Setup DNS servers and exporters
  hosts: dns_servers
  become: true
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Setup DNS resolution
  hosts: all
  become: true
  roles:
    - dns_resolve
  tags: dns

- name: Setup hosts' A records
  hosts: all
  become: true
  roles:
    - host_a_record
  tags: a_records

- name: Setup hosts' PTR records
  hosts: all
  become: true
  roles:
    - host_ptr_record
  tags: ptr_records

- name: Setup backup server functionality
  hosts: all
  become: true
  roles:
    - backup
  tags: backup

- name: Setup database servers and exporters
  hosts: db_servers
  become: true
  roles:
    - mysql
    - mysql_exporter
  tags: db

- name: Setup Prometheus server
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus
  tags: prom

- name: Setup Grafana
  hosts: grafana_servers
  become: true
  roles:
    - docker
    - grafana
  tags: grafana

- name: Setup proxy for internal services
  hosts: prometheus_servers:grafana_servers
  become: true
  roles:
    - nginx
  tags: proxy

- name: Setup InfluxDB
  hosts: influxdb_servers
  become: true
  roles:
    - influxdb
    - influxdb_exporter
  tags: influx

- name: Setup pinger
  hosts: pinger_servers
  become: true
  roles:
    - pinger
  tags:
    - pinger

- name: Setup application and web server
  hosts: web_servers
  become: true
  roles:
    - docker
    - agama
    - nginx
    - nginx_exporter
  tags: web

- name: Setup haproxy
  hosts: haproxy_servers
  become: true
  roles:
    - haproxy
    - haproxy_exporter
    - keepalived
    - keepalived_exporter
  tags:
    - haproxy
    - keepalived
