- name: Initial setup
  hosts: all
  become: true
  roles:
    - init
  tags: init

- name: Setup DNS servers and exporters
  hosts: dns_servers
  become: true
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Setup DNS resolution
  hosts: all
  become: true
  roles:
    - dns_resolve
  tags: dns

- name: Setup database servers and exporters
  hosts: db_servers
  become: true
  roles:
    - mysql
    - mysql_exporter
  tags: db

- name: Setup Prometheus server
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus
  tags: prom

- name: Setup Grafana
  hosts: grafana_servers
  become: true
  roles:
    - docker
    - grafana
  tags: grafana

- name: Setup InfluxDB
  hosts: influxdb_servers
  become: true
  roles:
    - influxdb
    - influxdb_exporter
  tags: influx

- name: Setup application and web server
  hosts: web_servers
  become: true
  roles:
    - docker
    - agama
    - nginx
    - nginx_exporter
  tags: web

- name: Setup pinger
  hosts: pinger_servers
  become: true
  roles:
    - pinger
  tags:
    - pinger
