- name: Restart pinger
  ansible.builtin.service:
    name: pinger
    state: restarted
    enabled: true

- name: Reload daemons # noqa: command-instead-of-module command-instead-of-shell no-changed-when
  ansible.builtin.shell: systemctl daemon-reload
