{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 3, "y": 0 },
   "targets": [
    {
     "alias": "Google.com",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\"::tag = 'google.com') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "dst::tag", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "Cloudflare.com",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\"::tag = 'google.com') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "dst::tag", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "alias": "Twitter.com",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\"::tag = 'google.com') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "dst::tag", "operator": "=", "value": "twitter.com" }
     ]
    }
   ]
  },
  {
   "title": "Service state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{job}}@{{instance}}" },
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{job}}@{{instance}}"
    },
    { "expr": "mysql_up", "legendFormat": "{{job}}@{{instance}}" },
    { "expr": "nginx_up", "legendFormat": "{{job}}@{{instance}}" }
   ]
  },
  {
   "title": "MySQL query rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=~\"select|show_status|update\"}[5m])",
     "legendFormat": "{{instance}}: {{command}}"
    }
   ]
  },
  {
   "title": "Nginx request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS query rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=~\"A|AAAA|NS|SRV\"}[5m])",
     "legendFormat": "{{instance}}: {{type}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}