- name: Add user 'agama'
  ansible.builtin.user:
    user: agama

- name: Create application directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    mode: '0700'

- name: Install dependencies
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql 

- name: Fetch and install application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/6b167d27bf2cc8786d4c54fd6cb0d9fabfb3918b/agama.py
    dest: /opt/agama/agama.py
    owner: agama
    mode: '0700' 
