- name: Add user 'backup' and generate SSH key
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Create directory /home/backup/restore
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present

- name: Place known_hosts file
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: root
    group: root
    mode: '0644'

- name: Add DNS record for backup server
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record_type: A
    dns_record_record: backup
    dns_record_value: '{{ backup_server_ip }}'
