- name: Place my.cnf file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    mode: "0400"
  notify: Restart mysql exporter
  no_log: true

- name: Install mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Create mysql user for exporter
  mysql_user:
    name: exporter
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Start service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true
