- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql

- name: Place configuration file
  ansible.builtin.copy:
    src: override.cnf 
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Start service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mysql_database }}.*:ALL"
