- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql

- name: Place configuration file
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
    owner: mysql
    mode: '0644'
  notify: Restart MySQL

- name: Create database
  community.mysql.mysql_db:
    name: '{{ mysql_database }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add user
  community.mysql.mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_password }}'
    host: '%'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mysql_database }}.*:ALL"

- name: Create directory /home/backup/mysql
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0700'

- name: Place my.cnf
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    mode: '0400'
    owner: '{{ mysql_backup_user }}'
  no_log: true

- name: Create backups MySQL user
  community.mysql.mysql_user:
    name: '{{ mysql_backup_user }}'
    password: '{{ mysql_backup_password }}'
    host: "%"
    priv:
      '*.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Place MySQL backup cron file
  ansible.builtin.template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    owner: root
    mode: '0644'

- name: Start service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
