- name: Add user pinger
  ansible.builtin.user:
    name: pinger

- name: Install fping
  ansible.builtin.apt:
    name: fping

- name: Create path
  ansible.builtin.file:
    path: /etc/pinger
    state: directory
    owner: pinger
    mode: '0700'

- name: Copy pinger service file
  ansible.builtin.copy:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
    owner: pinger
    mode: '0600'
  no_log: true
  notify:
    - Reload daemons
    - Restart pinger

- name: Copy pinger.sh
  ansible.builtin.template:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    owner: pinger
    group: pinger
    mode: '0777'
  notify:
    - Reload daemons
    - Restart pinger

- name: Copy pinger.conf.j2 template into /etc/pinger/pinger.conf
  ansible.builtin.template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
    owner: pinger
    mode: '0600'
  notify:
    - Reload daemons
    - Restart pinger

- name: Ensure pinger is running
  ansible.builtin.service:
    name: pinger
    state: started
    enabled: true
