- name: Install haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Place prometheus-haproxy-exporter config file
  ansible.builtin.template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
    owner: prometheus
    mode: '0600'
  notify: Restart haproxy-exporter

- name: Start exporter
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true
