- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus

- name: Place ARGS configuration file
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Place yml configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Start service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
