- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus

- name: Place ARGS configuration file
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    owner: prometheus
    mode: "0600"
  notify: Restart prometheus

- name: Place yml configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    mode: "0600"
  notify: Restart prometheus

- name: Start service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Add CNAME record
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record_record: "{{ service_cname_records.prometheus }}"
