- name: Install docker.io and python3-docker
  ansible.builtin.apt:
    name:
      - python3-docker
      - docker.io

- name: Start the Docker daemon
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# Development tools:
- name: Download and install lazydocker
  ansible.builtin.unarchive:
    src: https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker_version }}/lazydocker_{{ lazydocker_version }}_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: true
