- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_master_hostname

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_host: "{{ mysql_master_host }}"
    primary_user: "{{ mysql_replica_user }}"
    primary_password: "{{ mysql_replica_password }}"
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_master_hostname
  no_log: true

- name: Schedule Agama containers for restart
  ansible.builtin.set_fact:
    cacheable: true
    mysql_db_master_moved: true
