# - name: Ansible ping module
#   ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Enable node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1

- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest

- name: Place rsyslog conf file
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/rsyslog.d/telegraf.conf
  notify: Restart Rsyslog

- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes

# - name: Add user 'roman'
#   ansible.builtin.user:
#     user: roman

# - name: Add user 'juri'
#   ansible.builtin.user:
#     user: juri

# - name: Authorize key for user 'roman'
#   ansible.posix.authorized_key:
#     user: roman
#     key: https://github.com/romankuchin.keys

# - name: Authorize key for user 'juri'
#   ansible.posix.authorized_key:
#     user: juri
#     key: https://github.com/hudolejev.keys
