- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Enable node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1

- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog

- name: Place rsyslog conf file
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/rsyslog.d/telegraf.conf
    owner: root
    mode: '0444'
  notify: Restart Rsyslog

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
